### ISSUE TITLE
要不看看这个库？

### ISSUE THREAD

**Issue by Piasy** [yjfnypeu/Courier#1]
https://github.com/yatatsu/AutoBundle

或者这个：https://github.com/sockeqwe/fragmentargs

它们的 api 更简洁一点，也是比较成熟的轮子了 :)

**Comment by yjfnypeu** [comment]
的确，它们的api是比我的简单，其实我知道的还有一个
https://github.com/workarounds/bundler
也是你上面所说的那种逻辑，但是我个人比较喜欢能将所有传递参数都装入一个类中的。因为如果你界面传递参数多了。再加上一些内部本身就有的参数。混合在一块，阅读性太差了。

**Comment by yjfnypeu** [comment]
的确，它们的api是比我的简单，其实我知道的还有一个
https://github.com/workarounds/bundler
也是你上面所说的那种逻辑，但是我个人比较喜欢能将所有传递参数都装入一个类中的。因为如果你界面传递参数多了。再加上一些内部本身就有的参数。混合在一块，阅读性太差了。

**Comment by Piasy** [comment]
你的考虑也有道理，你的方案是把所有的参数声明都放到类的头部（注解中），各有千秋

**Comment by yjfnypeu** [comment]
嗯，多谢支持。
