### ISSUE TITLE
添加依赖报错

### ISSUE THREAD

**Issue by walorwang** [yjfnypeu/Courier#2]
Could not find org.lzh.compiler.lib:courier-compiler:0.1

**Comment by iwgang** [comment]
@Batows 

```
    compile 'org.lzh.compiler.courier:courier-api:0.1'
    apt 'org.lzh.compiler.courier:courier-compiler:0.1'
```

**Comment by yjfnypeu** [comment]
@Batows 多谢指出。已重新更新readme.

**Comment by zhujunjun** [comment]
为什么我项目里面使用这个LiveActivity_Dispatcher 呈现红色的呢？我在当前LiveActivity引用了@Params(fields = {
        @Field(name="url",type = String.class,),
        @Field(name = "title",type =String.class)
})

**Comment by zhujunjun** [comment]
编辑一下就有了~
